<?php

return [
    [
        'slug' => 'camisa-real-madrid-home',
        'nome' => 'Real Madrid 24/25 Stadium Home',
        'categoria' => 'Masculino',
        'descricao' => 'Camisa branca inspirada nos grandes momentos europeus, com tecido leve e acabamento premium para torcer ou jogar.',
        'preco' => 349.99,
        'estoque' => 12,
        'tamanho' => 'M',
        'imagem' => 'images/site/colecao-01.png',
    ],
    [
        'slug' => 'camisa-botafogo-home',
        'nome' => 'Botafogo 24/25 Stadium Home',
        'categoria' => 'Masculino',
        'descricao' => 'Listras tradicionais em uma camisa de estádio com caimento confortável e visual clássico.',
        'preco' => 299.99,
        'estoque' => 8,
        'tamanho' => 'G',
        'imagem' => 'images/site/colecao-02.png',
    ],
    [
        'slug' => 'camisa-flamengo-home',
        'nome' => 'Flamengo 24/25 Home',
        'categoria' => 'Masculino',
        'descricao' => 'Rubro-negra de presença forte, pronta para arquibancada, treino e uso casual.',
        'preco' => 349.99,
        'estoque' => 15,
        'tamanho' => 'M',
        'imagem' => 'images/site/banner-hero-alt.png',
    ],
    [
        'slug' => 'camisa-barcelona-home',
        'nome' => 'Barcelona 24/25 Home',
        'categoria' => 'Feminino',
        'descricao' => 'Modelo azul e grená com acabamento esportivo, pensado para conforto e estilo.',
        'preco' => 349.99,
        'estoque' => 10,
        'tamanho' => 'P',
        'imagem' => 'images/site/colecao-03.png',
    ],
    [
        'slug' => 'camisa-corinthians-black',
        'nome' => 'Corinthians 24/25 Black',
        'categoria' => 'Infantil',
        'descricao' => 'Camisa preta em visual urbano, com toque esportivo e acabamento leve.',
        'preco' => 299.99,
        'estoque' => 6,
        'tamanho' => 'GG',
        'imagem' => 'images/site/banner-personalizar.png',
    ],
];
